/* Generated by AN DISI Unibo */ 
package it.unibo.testHalt;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.contactEvent.platform.ContactEventPlatform;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.robotActor.sensors.SensorStreamSetter;
import it.unibo.robotActor.usb.USBTetherClientStreamer;
import rx.functions.Action1;

public class UserSensorStreamSetter extends SensorStreamSetter{
	public UserSensorStreamSetter( String actorId, IOutputView outView, USBTetherClientStreamer usbClientStreamer){
		super(actorId, outView,usbClientStreamer);
 	}
	
@Override
protected void setSubscribers(   ){
}

}
