/* Generated by AN DISI Unibo */ 
package it.unibo.testSensor;
import it.unibo.robotActor.utils.RobotSysKb;

public class AsynchActionKb {
private static int c=1;
	public static void setAsynchActions(){
		try {
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}
}
