/* Generated by AN DISI Unibo */ 
package it.unibo.testSensor;
import it.unibo.contactEvent.interfaces.IContactEventPlatform;
import it.unibo.contactEvent.platform.ContactEventPlatform;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.system.SituatedActiveObject;

public class EventSimulator extends SituatedActiveObject{
private IContactEventPlatform platform;
private int delay;
private String evId;
	public EventSimulator( IOutputView outView, String evId, int delay) throws Exception{
		super(outView,"eventSimul");
		this.evId = evId;
		this.delay = delay;
		platform = ContactEventPlatform.getPlatform();
	}
	@Override
	protected void doJob() throws Exception {		
		Thread.sleep(delay);	//Delay
		outView.addOutput("		**** RAISE EVENT ********* " + evId);
		platform.raiseEvent("simulator", evId, "simulated");
 	}
	@Override
	protected void startWork() throws Exception {
 	}
	@Override
	protected void endWork() throws Exception {
 	}
}
