/* Generated by AN DISI Unibo */ 
package it.unibo.testSensor;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.contactEvent.platform.ContactEventPlatform;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.robotActor.sensors.SensorStreamSetter;
import it.unibo.robotActor.usb.USBTetherClientStreamer;
import rx.functions.Action1;

public class UserSensorStreamSetter extends SensorStreamSetter{
private  Action1<String> halt_action = new Action1<String>() {
		@Override
		public void call(String s) {
 		try {
 			//distance(43,forward, front)
 			println("halt_action: " + s);
 			Struct st = (Struct) Term.createTerm(s);
 			int d = Integer.parseInt(""+st.getArg(0));
 			if( d < 20 )
 				ContactEventPlatform.getPlatform().raiseEvent("syshalt", "halt", ""+d);
 	 	} catch (Exception e) {
			e.printStackTrace();
		}
 		}//call
};
	public UserSensorStreamSetter( String actorId, IOutputView outView, USBTetherClientStreamer usbClientStreamer){
		super(actorId, outView,usbClientStreamer);
 	}
	
@Override
protected void setSubscribers(   ){
	diatanceStream.subscribe( halt_action ); 
}

}
