/* Generated by AN DISI Unibo */ 
package it.unibo.robotAreaSystem;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.robotActor.interpreted.action.AsynchAction;
public abstract class AskForPhotoSupport extends AsynchAction {
 
 	public AskForPhotoSupport() throws Exception{
 		super();
 	}
	public AskForPhotoSupport(String name, boolean cancompensate, String terminationEvId, String answerEvId, IOutputView outView, 
			long maxduration )
			throws Exception {
		super(name, cancompensate, terminationEvId, answerEvId, outView, maxduration);
 	}

  	@Override
 	public void execAction() throws Exception {
 		answer= actionBody();
 	}
	/*
	* This operation should be written by the user
	*/
	protected abstract String actionBody() throws Exception;
	/*
		println( getName() + " arg=" + arg + 
			" terminationEvId=" + terminationEvId  + " answerEvId=" + answerEvId + 
			" maxduration=" + maxduration);
		Thread.sleep(maxduration);
		answer="answer(askForPhoto,"+ arg + ")";
		println("askForPhoto ENDS answer=" + answer );
	*/
}
