/* Generated by AN DISI Unibo */ 
package it.unibo.robotAreaSystem;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.contactEvent.platform.TaskComponent;
import it.unibo.robotActor.utils.RobotSysKb;
import it.unibo.robotActor.interpreted.action.IActionHandler;

public abstract class EvAreaTaskSupport extends TaskComponent implements IActionHandler{
protected IEventItem curEvent = null;
	public EvAreaTaskSupport(String name, String[] eventId ) throws Exception {
		super(name, RobotSysKb.robotActorCtx, eventId, RobotSysKb.stdOutView);
		curstate = "stateInit";
  	} 
 	@Override
	protected void stateControl() throws Exception {
 		if( ! this.isTerminated() ){	//NO MORE WHILE		
			if( curstate.equals("stateInit")){ stateInit();  }
			else if( curstate.equals("stateHadleEvent")){ stateHadleEvent();  }
 		};
	}
	protected void stateInit()throws Exception{
		//showMsg("START ");
		String[] events 	= inputSymbolEvents;
		String[] nextStates = new String[]{ "stateHadleEvent"  };
		transitions(events,nextStates);
   	}
	protected void stateHadleEvent()throws Exception{
		curEvent 	 = this.getEventItem();
		handleEvent(curEvent);
 		showMsg("ENDS " );
 		terminate();	  
	}
	protected abstract void handleEvent(IEventItem curEvent);
	
	@Override
	public String getHandlerName() {
		return getName();
	}
	@Override
	public void addEventId(String evId) {
	}
	protected void showEvent(IEventItem curEvent){
 		String evId  = curEvent.getEventId() ;
		String evMsg = curEvent.getMsg() ;
   		String msg = getName() + ":" + evId + " msg=" + evMsg + " emitter=" + curEvent.getSubj()   ;
		showMsg( "--------------------------------------------------" );	
		showMsg( msg );				 
		showMsg( "--------------------------------------------------" );	
	}
}
