
/* Generated by AN DISI Unibo */ 
package it.unibo.robotAreaSystem;
import java.io.InputStream;
import java.io.FileInputStream;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.qactors.ActorContext;  	
import it.unibo.robotActor.utils.RobotSysKb;

	public class MainPhotographerCtx extends ActorContext{
 		public MainPhotographerCtx(String name, IOutputView outView,
			InputStream sysKbStream, InputStream sysRulesStream  )
			throws Exception {
		super(name, outView, sysKbStream, sysRulesStream);
  	}
	@Override
	public void configure(){
 		try {
 			new PhotographerActor("photographeractor", this, outView);
 		} catch (Exception e) {
			println(getName() + " ERROR " + e.getMessage() );
		}	
	}

 	public static void main(String[] args) throws Exception {
		InputStream sysKbStream = new FileInputStream("robotAreaSystem.pl");
		InputStream sysRulesStream = new FileInputStream("sysRules.pl");
		new MainPhotographerCtx("photographerctx", RobotSysKb.stdOutView, sysKbStream, sysRulesStream ).configure();
	}


 }
